/**
 * generated by Xtext 2.10.0
 */
package des.missionrobot.robotDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link des.missionrobot.robotDSL.Behavior#getName <em>Name</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Behavior#getPrio <em>Prio</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Behavior#getDeviceList <em>Device List</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Behavior#getActionList <em>Action List</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Behavior#getTriggerList <em>Trigger List</em>}</li>
 * </ul>
 *
 * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior()
 * @model
 * @generated
 */
public interface Behavior extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Behavior#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prio</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prio</em>' attribute.
   * @see #setPrio(int)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior_Prio()
   * @model
   * @generated
   */
  int getPrio();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Behavior#getPrio <em>Prio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prio</em>' attribute.
   * @see #getPrio()
   * @generated
   */
  void setPrio(int value);

  /**
   * Returns the value of the '<em><b>Device List</b></em>' reference list.
   * The list contents are of type {@link des.missionrobot.robotDSL.Device}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Device List</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device List</em>' reference list.
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior_DeviceList()
   * @model
   * @generated
   */
  EList<Device> getDeviceList();

  /**
   * Returns the value of the '<em><b>Action List</b></em>' containment reference list.
   * The list contents are of type {@link des.missionrobot.robotDSL.Action}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action List</em>' containment reference list.
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior_ActionList()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActionList();

  /**
   * Returns the value of the '<em><b>Trigger List</b></em>' containment reference list.
   * The list contents are of type {@link des.missionrobot.robotDSL.Trigger}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger List</em>' containment reference list.
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getBehavior_TriggerList()
   * @model containment="true"
   * @generated
   */
  EList<Trigger> getTriggerList();

} // Behavior
