/**
 * generated by Xtext 2.10.0
 */
package des.missionrobot.robotDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Movement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see des.missionrobot.robotDSL.RobotDSLPackage#getMovement()
 * @model
 * @generated
 */
public interface Movement extends EObject
{
} // Movement
