/**
 * generated by Xtext 2.10.0
 */
package des.missionrobot.robotDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see des.missionrobot.robotDSL.RobotDSLFactory
 * @model kind="package"
 * @generated
 */
public interface RobotDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "robotDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.missionrobot.des/RobotDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "robotDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RobotDSLPackage eINSTANCE = des.missionrobot.robotDSL.impl.RobotDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.MissionsImpl <em>Missions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.MissionsImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMissions()
   * @generated
   */
  int MISSIONS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Mission List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSIONS__MISSION_LIST = 1;

  /**
   * The number of structural features of the '<em>Missions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.MissionImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Flags List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__FLAGS_LIST = 1;

  /**
   * The feature id for the '<em><b>Task List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TASK_LIST = 2;

  /**
   * The feature id for the '<em><b>Goal Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__GOAL_EVENTS = 3;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TIMEOUT = 4;

  /**
   * The feature id for the '<em><b>Finish Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__FINISH_ACTIONS = 5;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.TaskImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIO = 1;

  /**
   * The feature id for the '<em><b>Trigger List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TRIGGER_LIST = 2;

  /**
   * The feature id for the '<em><b>Action List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION_LIST = 3;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.ActionImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The feature id for the '<em><b>Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DIR = 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DURATION = 1;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SPEED = 2;

  /**
   * The feature id for the '<em><b>Degr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DEGR = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__OP = 4;

  /**
   * The feature id for the '<em><b>Sound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SOUND = 5;

  /**
   * The feature id for the '<em><b>Flag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__FLAG = 6;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__BOOL = 7;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.TriggerImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 4;

  /**
   * The feature id for the '<em><b>Bool Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__BOOL_TYPE = 0;

  /**
   * The feature id for the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__NEG = 1;

  /**
   * The feature id for the '<em><b>Flag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__FLAG = 2;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__SENSOR = 3;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__COLOR = 4;

  /**
   * The feature id for the '<em><b>Dist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__DIST = 5;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.DistanceImpl <em>Distance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.DistanceImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDistance()
   * @generated
   */
  int DISTANCE = 5;

  /**
   * The feature id for the '<em><b>Range Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE__RANGE_BOOL = 0;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE__DISTANCE = 1;

  /**
   * The number of structural features of the '<em>Distance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.FlagImpl <em>Flag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.FlagImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getFlag()
   * @generated
   */
  int FLAG = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLAG__NAME = 0;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLAG__BOOL = 1;

  /**
   * The number of structural features of the '<em>Flag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLAG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.TimeImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTime()
   * @generated
   */
  int TIME = 7;

  /**
   * The feature id for the '<em><b>Sec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__SEC = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Direction
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 8;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Speed
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSpeed()
   * @generated
   */
  int SPEED = 9;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.ArmOp
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getArmOp()
   * @generated
   */
  int ARM_OP = 10;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Sound
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSound()
   * @generated
   */
  int SOUND = 11;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Sensor
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 12;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Color <em>Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Color
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getColor()
   * @generated
   */
  int COLOR = 13;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Bool
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBool()
   * @generated
   */
  int BOOL = 14;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Negation <em>Negation</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Negation
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getNegation()
   * @generated
   */
  int NEGATION = 15;


  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Missions <em>Missions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Missions</em>'.
   * @see des.missionrobot.robotDSL.Missions
   * @generated
   */
  EClass getMissions();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Missions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Missions#getName()
   * @see #getMissions()
   * @generated
   */
  EAttribute getMissions_Name();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Missions#getMissionList <em>Mission List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mission List</em>'.
   * @see des.missionrobot.robotDSL.Missions#getMissionList()
   * @see #getMissions()
   * @generated
   */
  EReference getMissions_MissionList();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see des.missionrobot.robotDSL.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Mission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Mission#getName()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Name();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Mission#getFlagsList <em>Flags List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Flags List</em>'.
   * @see des.missionrobot.robotDSL.Mission#getFlagsList()
   * @see #getMission()
   * @generated
   */
  EReference getMission_FlagsList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Mission#getTaskList <em>Task List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task List</em>'.
   * @see des.missionrobot.robotDSL.Mission#getTaskList()
   * @see #getMission()
   * @generated
   */
  EReference getMission_TaskList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Mission#getGoalEvents <em>Goal Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Goal Events</em>'.
   * @see des.missionrobot.robotDSL.Mission#getGoalEvents()
   * @see #getMission()
   * @generated
   */
  EReference getMission_GoalEvents();

  /**
   * Returns the meta object for the containment reference '{@link des.missionrobot.robotDSL.Mission#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timeout</em>'.
   * @see des.missionrobot.robotDSL.Mission#getTimeout()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Timeout();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Mission#getFinishActions <em>Finish Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Finish Actions</em>'.
   * @see des.missionrobot.robotDSL.Mission#getFinishActions()
   * @see #getMission()
   * @generated
   */
  EReference getMission_FinishActions();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see des.missionrobot.robotDSL.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Task#getPrio <em>Prio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prio</em>'.
   * @see des.missionrobot.robotDSL.Task#getPrio()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Prio();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Task#getTriggerList <em>Trigger List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trigger List</em>'.
   * @see des.missionrobot.robotDSL.Task#getTriggerList()
   * @see #getTask()
   * @generated
   */
  EReference getTask_TriggerList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Task#getActionList <em>Action List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action List</em>'.
   * @see des.missionrobot.robotDSL.Task#getActionList()
   * @see #getTask()
   * @generated
   */
  EReference getTask_ActionList();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see des.missionrobot.robotDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDir <em>Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dir</em>'.
   * @see des.missionrobot.robotDSL.Action#getDir()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Dir();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see des.missionrobot.robotDSL.Action#getDuration()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Duration();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see des.missionrobot.robotDSL.Action#getSpeed()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Speed();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDegr <em>Degr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degr</em>'.
   * @see des.missionrobot.robotDSL.Action#getDegr()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Degr();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see des.missionrobot.robotDSL.Action#getOp()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Op();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getSound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sound</em>'.
   * @see des.missionrobot.robotDSL.Action#getSound()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Sound();

  /**
   * Returns the meta object for the reference '{@link des.missionrobot.robotDSL.Action#getFlag <em>Flag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Flag</em>'.
   * @see des.missionrobot.robotDSL.Action#getFlag()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Flag();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see des.missionrobot.robotDSL.Action#getBool()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Bool();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see des.missionrobot.robotDSL.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getBoolType <em>Bool Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Type</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getBoolType()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_BoolType();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getNeg <em>Neg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Neg</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getNeg()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Neg();

  /**
   * Returns the meta object for the reference '{@link des.missionrobot.robotDSL.Trigger#getFlag <em>Flag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Flag</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getFlag()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Flag();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sensor</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getSensor()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Sensor();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getColor()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Color();

  /**
   * Returns the meta object for the containment reference '{@link des.missionrobot.robotDSL.Trigger#getDist <em>Dist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dist</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getDist()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Dist();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Distance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distance</em>'.
   * @see des.missionrobot.robotDSL.Distance
   * @generated
   */
  EClass getDistance();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Distance#getRangeBool <em>Range Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Range Bool</em>'.
   * @see des.missionrobot.robotDSL.Distance#getRangeBool()
   * @see #getDistance()
   * @generated
   */
  EAttribute getDistance_RangeBool();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Distance#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see des.missionrobot.robotDSL.Distance#getDistance()
   * @see #getDistance()
   * @generated
   */
  EAttribute getDistance_Distance();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Flag <em>Flag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flag</em>'.
   * @see des.missionrobot.robotDSL.Flag
   * @generated
   */
  EClass getFlag();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Flag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Flag#getName()
   * @see #getFlag()
   * @generated
   */
  EAttribute getFlag_Name();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Flag#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see des.missionrobot.robotDSL.Flag#getBool()
   * @see #getFlag()
   * @generated
   */
  EAttribute getFlag_Bool();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see des.missionrobot.robotDSL.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Time#getSec <em>Sec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sec</em>'.
   * @see des.missionrobot.robotDSL.Time#getSec()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Sec();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see des.missionrobot.robotDSL.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Speed</em>'.
   * @see des.missionrobot.robotDSL.Speed
   * @generated
   */
  EEnum getSpeed();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Arm Op</em>'.
   * @see des.missionrobot.robotDSL.ArmOp
   * @generated
   */
  EEnum getArmOp();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sound</em>'.
   * @see des.missionrobot.robotDSL.Sound
   * @generated
   */
  EEnum getSound();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sensor</em>'.
   * @see des.missionrobot.robotDSL.Sensor
   * @generated
   */
  EEnum getSensor();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color</em>'.
   * @see des.missionrobot.robotDSL.Color
   * @generated
   */
  EEnum getColor();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool</em>'.
   * @see des.missionrobot.robotDSL.Bool
   * @generated
   */
  EEnum getBool();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Negation <em>Negation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Negation</em>'.
   * @see des.missionrobot.robotDSL.Negation
   * @generated
   */
  EEnum getNegation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RobotDSLFactory getRobotDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.MissionsImpl <em>Missions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.MissionsImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMissions()
     * @generated
     */
    EClass MISSIONS = eINSTANCE.getMissions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSIONS__NAME = eINSTANCE.getMissions_Name();

    /**
     * The meta object literal for the '<em><b>Mission List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSIONS__MISSION_LIST = eINSTANCE.getMissions_MissionList();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.MissionImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__NAME = eINSTANCE.getMission_Name();

    /**
     * The meta object literal for the '<em><b>Flags List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__FLAGS_LIST = eINSTANCE.getMission_FlagsList();

    /**
     * The meta object literal for the '<em><b>Task List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TASK_LIST = eINSTANCE.getMission_TaskList();

    /**
     * The meta object literal for the '<em><b>Goal Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__GOAL_EVENTS = eINSTANCE.getMission_GoalEvents();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TIMEOUT = eINSTANCE.getMission_Timeout();

    /**
     * The meta object literal for the '<em><b>Finish Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__FINISH_ACTIONS = eINSTANCE.getMission_FinishActions();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.TaskImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Prio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PRIO = eINSTANCE.getTask_Prio();

    /**
     * The meta object literal for the '<em><b>Trigger List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__TRIGGER_LIST = eINSTANCE.getTask_TriggerList();

    /**
     * The meta object literal for the '<em><b>Action List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ACTION_LIST = eINSTANCE.getTask_ActionList();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.ActionImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DIR = eINSTANCE.getAction_Dir();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DURATION = eINSTANCE.getAction_Duration();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__SPEED = eINSTANCE.getAction_Speed();

    /**
     * The meta object literal for the '<em><b>Degr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DEGR = eINSTANCE.getAction_Degr();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__OP = eINSTANCE.getAction_Op();

    /**
     * The meta object literal for the '<em><b>Sound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__SOUND = eINSTANCE.getAction_Sound();

    /**
     * The meta object literal for the '<em><b>Flag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__FLAG = eINSTANCE.getAction_Flag();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__BOOL = eINSTANCE.getAction_Bool();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.TriggerImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Bool Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__BOOL_TYPE = eINSTANCE.getTrigger_BoolType();

    /**
     * The meta object literal for the '<em><b>Neg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__NEG = eINSTANCE.getTrigger_Neg();

    /**
     * The meta object literal for the '<em><b>Flag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__FLAG = eINSTANCE.getTrigger_Flag();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__SENSOR = eINSTANCE.getTrigger_Sensor();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__COLOR = eINSTANCE.getTrigger_Color();

    /**
     * The meta object literal for the '<em><b>Dist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__DIST = eINSTANCE.getTrigger_Dist();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.DistanceImpl <em>Distance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.DistanceImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDistance()
     * @generated
     */
    EClass DISTANCE = eINSTANCE.getDistance();

    /**
     * The meta object literal for the '<em><b>Range Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTANCE__RANGE_BOOL = eINSTANCE.getDistance_RangeBool();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTANCE__DISTANCE = eINSTANCE.getDistance_Distance();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.FlagImpl <em>Flag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.FlagImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getFlag()
     * @generated
     */
    EClass FLAG = eINSTANCE.getFlag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLAG__NAME = eINSTANCE.getFlag_Name();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLAG__BOOL = eINSTANCE.getFlag_Bool();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.TimeImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Sec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__SEC = eINSTANCE.getTime_Sec();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Direction
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Speed
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSpeed()
     * @generated
     */
    EEnum SPEED = eINSTANCE.getSpeed();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.ArmOp
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getArmOp()
     * @generated
     */
    EEnum ARM_OP = eINSTANCE.getArmOp();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Sound
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSound()
     * @generated
     */
    EEnum SOUND = eINSTANCE.getSound();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Sensor
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSensor()
     * @generated
     */
    EEnum SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Color <em>Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Color
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getColor()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Bool
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBool()
     * @generated
     */
    EEnum BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Negation <em>Negation</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Negation
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getNegation()
     * @generated
     */
    EEnum NEGATION = eINSTANCE.getNegation();

  }

} //RobotDSLPackage
