/**
 * generated by Xtext 2.10.0
 */
package des.missionrobot.robotDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see des.missionrobot.robotDSL.RobotDSLFactory
 * @model kind="package"
 * @generated
 */
public interface RobotDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "robotDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.missionrobot.des/RobotDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "robotDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RobotDSLPackage eINSTANCE = des.missionrobot.robotDSL.impl.RobotDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.MissionListImpl <em>Mission List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.MissionListImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMissionList()
   * @generated
   */
  int MISSION_LIST = 0;

  /**
   * The feature id for the '<em><b>Mission List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_LIST__MISSION_LIST = 0;

  /**
   * The number of structural features of the '<em>Mission List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.MissionImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Behavior List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__BEHAVIOR_LIST = 1;

  /**
   * The feature id for the '<em><b>Goal Events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__GOAL_EVENTS = 2;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.BehaviorImpl <em>Behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.BehaviorImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBehavior()
   * @generated
   */
  int BEHAVIOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__PRIO = 1;

  /**
   * The feature id for the '<em><b>Trigger List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__TRIGGER_LIST = 2;

  /**
   * The feature id for the '<em><b>Reaction List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__REACTION_LIST = 3;

  /**
   * The feature id for the '<em><b>Action List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__ACTION_LIST = 4;

  /**
   * The number of structural features of the '<em>Behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.ActionImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The feature id for the '<em><b>Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DIR = 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DURATION = 1;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SPEED = 2;

  /**
   * The feature id for the '<em><b>Degr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__DEGR = 3;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__OP = 4;

  /**
   * The feature id for the '<em><b>Sound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__SOUND = 5;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.ReactionImpl <em>Reaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.ReactionImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getReaction()
   * @generated
   */
  int REACTION = 4;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACTION__EVENT = 0;

  /**
   * The feature id for the '<em><b>Reactions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACTION__REACTIONS = 1;

  /**
   * The number of structural features of the '<em>Reaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.EventImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Repeat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__REPEAT = 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__TIME = 2;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.impl.TriggerImpl
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 6;

  /**
   * The feature id for the '<em><b>Bool Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__BOOL_TYPE = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__EVENT = 1;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__SENSOR = 2;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__COLOR = 3;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__BOOL = 4;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__DISTANCE = 5;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Direction
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 7;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Speed
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSpeed()
   * @generated
   */
  int SPEED = 8;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.ArmOp
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getArmOp()
   * @generated
   */
  int ARM_OP = 9;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Sound
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSound()
   * @generated
   */
  int SOUND = 10;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Sensor
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 11;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Color <em>Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Color
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getColor()
   * @generated
   */
  int COLOR = 12;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Bool
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBool()
   * @generated
   */
  int BOOL = 13;

  /**
   * The meta object id for the '{@link des.missionrobot.robotDSL.Repeat <em>Repeat</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see des.missionrobot.robotDSL.Repeat
   * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getRepeat()
   * @generated
   */
  int REPEAT = 14;


  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.MissionList <em>Mission List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission List</em>'.
   * @see des.missionrobot.robotDSL.MissionList
   * @generated
   */
  EClass getMissionList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.MissionList#getMissionList <em>Mission List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mission List</em>'.
   * @see des.missionrobot.robotDSL.MissionList#getMissionList()
   * @see #getMissionList()
   * @generated
   */
  EReference getMissionList_MissionList();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see des.missionrobot.robotDSL.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Mission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Mission#getName()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Name();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Mission#getBehaviorList <em>Behavior List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Behavior List</em>'.
   * @see des.missionrobot.robotDSL.Mission#getBehaviorList()
   * @see #getMission()
   * @generated
   */
  EReference getMission_BehaviorList();

  /**
   * Returns the meta object for the reference list '{@link des.missionrobot.robotDSL.Mission#getGoalEvents <em>Goal Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Goal Events</em>'.
   * @see des.missionrobot.robotDSL.Mission#getGoalEvents()
   * @see #getMission()
   * @generated
   */
  EReference getMission_GoalEvents();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Behavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behavior</em>'.
   * @see des.missionrobot.robotDSL.Behavior
   * @generated
   */
  EClass getBehavior();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Behavior#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Behavior#getName()
   * @see #getBehavior()
   * @generated
   */
  EAttribute getBehavior_Name();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Behavior#getPrio <em>Prio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prio</em>'.
   * @see des.missionrobot.robotDSL.Behavior#getPrio()
   * @see #getBehavior()
   * @generated
   */
  EAttribute getBehavior_Prio();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Behavior#getTriggerList <em>Trigger List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trigger List</em>'.
   * @see des.missionrobot.robotDSL.Behavior#getTriggerList()
   * @see #getBehavior()
   * @generated
   */
  EReference getBehavior_TriggerList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Behavior#getReactionList <em>Reaction List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Reaction List</em>'.
   * @see des.missionrobot.robotDSL.Behavior#getReactionList()
   * @see #getBehavior()
   * @generated
   */
  EReference getBehavior_ReactionList();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Behavior#getActionList <em>Action List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action List</em>'.
   * @see des.missionrobot.robotDSL.Behavior#getActionList()
   * @see #getBehavior()
   * @generated
   */
  EReference getBehavior_ActionList();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see des.missionrobot.robotDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDir <em>Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dir</em>'.
   * @see des.missionrobot.robotDSL.Action#getDir()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Dir();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see des.missionrobot.robotDSL.Action#getDuration()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Duration();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see des.missionrobot.robotDSL.Action#getSpeed()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Speed();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getDegr <em>Degr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degr</em>'.
   * @see des.missionrobot.robotDSL.Action#getDegr()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Degr();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see des.missionrobot.robotDSL.Action#getOp()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Op();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Action#getSound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sound</em>'.
   * @see des.missionrobot.robotDSL.Action#getSound()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Sound();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Reaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reaction</em>'.
   * @see des.missionrobot.robotDSL.Reaction
   * @generated
   */
  EClass getReaction();

  /**
   * Returns the meta object for the reference '{@link des.missionrobot.robotDSL.Reaction#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see des.missionrobot.robotDSL.Reaction#getEvent()
   * @see #getReaction()
   * @generated
   */
  EReference getReaction_Event();

  /**
   * Returns the meta object for the containment reference list '{@link des.missionrobot.robotDSL.Reaction#getReactions <em>Reactions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Reactions</em>'.
   * @see des.missionrobot.robotDSL.Reaction#getReactions()
   * @see #getReaction()
   * @generated
   */
  EReference getReaction_Reactions();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see des.missionrobot.robotDSL.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see des.missionrobot.robotDSL.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Event#getRepeat <em>Repeat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Repeat</em>'.
   * @see des.missionrobot.robotDSL.Event#getRepeat()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Repeat();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Event#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see des.missionrobot.robotDSL.Event#getTime()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Time();

  /**
   * Returns the meta object for class '{@link des.missionrobot.robotDSL.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see des.missionrobot.robotDSL.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getBoolType <em>Bool Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Type</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getBoolType()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_BoolType();

  /**
   * Returns the meta object for the reference '{@link des.missionrobot.robotDSL.Trigger#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getEvent()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Event();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sensor</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getSensor()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Sensor();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getColor()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Color();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getBool()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Bool();

  /**
   * Returns the meta object for the attribute '{@link des.missionrobot.robotDSL.Trigger#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see des.missionrobot.robotDSL.Trigger#getDistance()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Distance();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see des.missionrobot.robotDSL.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Speed</em>'.
   * @see des.missionrobot.robotDSL.Speed
   * @generated
   */
  EEnum getSpeed();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Arm Op</em>'.
   * @see des.missionrobot.robotDSL.ArmOp
   * @generated
   */
  EEnum getArmOp();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sound</em>'.
   * @see des.missionrobot.robotDSL.Sound
   * @generated
   */
  EEnum getSound();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sensor</em>'.
   * @see des.missionrobot.robotDSL.Sensor
   * @generated
   */
  EEnum getSensor();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color</em>'.
   * @see des.missionrobot.robotDSL.Color
   * @generated
   */
  EEnum getColor();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool</em>'.
   * @see des.missionrobot.robotDSL.Bool
   * @generated
   */
  EEnum getBool();

  /**
   * Returns the meta object for enum '{@link des.missionrobot.robotDSL.Repeat <em>Repeat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Repeat</em>'.
   * @see des.missionrobot.robotDSL.Repeat
   * @generated
   */
  EEnum getRepeat();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RobotDSLFactory getRobotDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.MissionListImpl <em>Mission List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.MissionListImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMissionList()
     * @generated
     */
    EClass MISSION_LIST = eINSTANCE.getMissionList();

    /**
     * The meta object literal for the '<em><b>Mission List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION_LIST__MISSION_LIST = eINSTANCE.getMissionList_MissionList();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.MissionImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__NAME = eINSTANCE.getMission_Name();

    /**
     * The meta object literal for the '<em><b>Behavior List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__BEHAVIOR_LIST = eINSTANCE.getMission_BehaviorList();

    /**
     * The meta object literal for the '<em><b>Goal Events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__GOAL_EVENTS = eINSTANCE.getMission_GoalEvents();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.BehaviorImpl <em>Behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.BehaviorImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBehavior()
     * @generated
     */
    EClass BEHAVIOR = eINSTANCE.getBehavior();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIOR__NAME = eINSTANCE.getBehavior_Name();

    /**
     * The meta object literal for the '<em><b>Prio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIOR__PRIO = eINSTANCE.getBehavior_Prio();

    /**
     * The meta object literal for the '<em><b>Trigger List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__TRIGGER_LIST = eINSTANCE.getBehavior_TriggerList();

    /**
     * The meta object literal for the '<em><b>Reaction List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__REACTION_LIST = eINSTANCE.getBehavior_ReactionList();

    /**
     * The meta object literal for the '<em><b>Action List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__ACTION_LIST = eINSTANCE.getBehavior_ActionList();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.ActionImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DIR = eINSTANCE.getAction_Dir();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DURATION = eINSTANCE.getAction_Duration();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__SPEED = eINSTANCE.getAction_Speed();

    /**
     * The meta object literal for the '<em><b>Degr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__DEGR = eINSTANCE.getAction_Degr();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__OP = eINSTANCE.getAction_Op();

    /**
     * The meta object literal for the '<em><b>Sound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__SOUND = eINSTANCE.getAction_Sound();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.ReactionImpl <em>Reaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.ReactionImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getReaction()
     * @generated
     */
    EClass REACTION = eINSTANCE.getReaction();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REACTION__EVENT = eINSTANCE.getReaction_Event();

    /**
     * The meta object literal for the '<em><b>Reactions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REACTION__REACTIONS = eINSTANCE.getReaction_Reactions();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.EventImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Repeat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__REPEAT = eINSTANCE.getEvent_Repeat();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__TIME = eINSTANCE.getEvent_Time();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.impl.TriggerImpl
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Bool Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__BOOL_TYPE = eINSTANCE.getTrigger_BoolType();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__EVENT = eINSTANCE.getTrigger_Event();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__SENSOR = eINSTANCE.getTrigger_Sensor();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__COLOR = eINSTANCE.getTrigger_Color();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__BOOL = eINSTANCE.getTrigger_Bool();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__DISTANCE = eINSTANCE.getTrigger_Distance();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Direction
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Speed <em>Speed</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Speed
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSpeed()
     * @generated
     */
    EEnum SPEED = eINSTANCE.getSpeed();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.ArmOp <em>Arm Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.ArmOp
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getArmOp()
     * @generated
     */
    EEnum ARM_OP = eINSTANCE.getArmOp();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Sound <em>Sound</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Sound
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSound()
     * @generated
     */
    EEnum SOUND = eINSTANCE.getSound();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Sensor <em>Sensor</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Sensor
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getSensor()
     * @generated
     */
    EEnum SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Color <em>Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Color
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getColor()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Bool <em>Bool</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Bool
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getBool()
     * @generated
     */
    EEnum BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '{@link des.missionrobot.robotDSL.Repeat <em>Repeat</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see des.missionrobot.robotDSL.Repeat
     * @see des.missionrobot.robotDSL.impl.RobotDSLPackageImpl#getRepeat()
     * @generated
     */
    EEnum REPEAT = eINSTANCE.getRepeat();

  }

} //RobotDSLPackage
