/**
 * generated by Xtext 2.10.0
 */
package des.missionrobot.robotDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getBoolType <em>Bool Type</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getNeg <em>Neg</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getFlag <em>Flag</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getSensor <em>Sensor</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getColor <em>Color</em>}</li>
 *   <li>{@link des.missionrobot.robotDSL.Trigger#getDist <em>Dist</em>}</li>
 * </ul>
 *
 * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger()
 * @model
 * @generated
 */
public interface Trigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Bool Type</b></em>' attribute.
   * The literals are from the enumeration {@link des.missionrobot.robotDSL.Bool}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Type</em>' attribute.
   * @see des.missionrobot.robotDSL.Bool
   * @see #setBoolType(Bool)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_BoolType()
   * @model
   * @generated
   */
  Bool getBoolType();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getBoolType <em>Bool Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Type</em>' attribute.
   * @see des.missionrobot.robotDSL.Bool
   * @see #getBoolType()
   * @generated
   */
  void setBoolType(Bool value);

  /**
   * Returns the value of the '<em><b>Neg</b></em>' attribute.
   * The literals are from the enumeration {@link des.missionrobot.robotDSL.Negation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg</em>' attribute.
   * @see des.missionrobot.robotDSL.Negation
   * @see #setNeg(Negation)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_Neg()
   * @model
   * @generated
   */
  Negation getNeg();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getNeg <em>Neg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg</em>' attribute.
   * @see des.missionrobot.robotDSL.Negation
   * @see #getNeg()
   * @generated
   */
  void setNeg(Negation value);

  /**
   * Returns the value of the '<em><b>Flag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Flag</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flag</em>' reference.
   * @see #setFlag(Flag)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_Flag()
   * @model
   * @generated
   */
  Flag getFlag();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getFlag <em>Flag</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flag</em>' reference.
   * @see #getFlag()
   * @generated
   */
  void setFlag(Flag value);

  /**
   * Returns the value of the '<em><b>Sensor</b></em>' attribute.
   * The literals are from the enumeration {@link des.missionrobot.robotDSL.Sensor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sensor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' attribute.
   * @see des.missionrobot.robotDSL.Sensor
   * @see #setSensor(Sensor)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_Sensor()
   * @model
   * @generated
   */
  Sensor getSensor();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getSensor <em>Sensor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor</em>' attribute.
   * @see des.missionrobot.robotDSL.Sensor
   * @see #getSensor()
   * @generated
   */
  void setSensor(Sensor value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link des.missionrobot.robotDSL.Color}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see des.missionrobot.robotDSL.Color
   * @see #setColor(Color)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_Color()
   * @model
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see des.missionrobot.robotDSL.Color
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

  /**
   * Returns the value of the '<em><b>Dist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dist</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dist</em>' containment reference.
   * @see #setDist(Distance)
   * @see des.missionrobot.robotDSL.RobotDSLPackage#getTrigger_Dist()
   * @model containment="true"
   * @generated
   */
  Distance getDist();

  /**
   * Sets the value of the '{@link des.missionrobot.robotDSL.Trigger#getDist <em>Dist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dist</em>' containment reference.
   * @see #getDist()
   * @generated
   */
  void setDist(Distance value);

} // Trigger
